extends: stylelint-config-sass-guidelines
rules:
    indentation: 4
    max-nesting-depth: 2
    scss/selector-no-redundant-nesting-selector: null
    selector-class-pattern:
      - "^[A-Za-z]+(__[a-z-]+)*(--[a-z-]+)*$"
      - { resolveNestedSelectors: true }
