---
language: node_js
node_js: 8.5

sudo: false
dist: trusty

addons:
  chrome: stable

env:
  global:
    - SUPPRESS_NO_CONFIG_WARNING=true

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache # includes bowers cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower
  - bower --version

install:
  - yarn --prefer-offline --pure-lockfile --ignore-engines
  - bower install --config.interactive=false

script:
  - yarn test
